CREATE TABLE Events (
    EventID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Date DATE NOT NULL,
    Time DATETIME NOT NULL,
    Type VARCHAR(50) NOT NULL,
    Capacity INT NOT NULL
);

CREATE TABLE Customers (
    CustomerID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    CreditCardDetails VARCHAR(20) NOT NULL
);

CREATE TABLE Tickets (
    TicketID INT AUTO_INCREMENT PRIMARY KEY,
    EventID INT NOT NULL,
    Type VARCHAR(50) NOT NULL,
    Price FLOAT NOT NULL,
    Availability INT NOT NULL,
    FOREIGN KEY (EventID) REFERENCES Events(EventID)
);

CREATE TABLE Reservations (
    ReservationID INT AUTO_INCREMENT PRIMARY KEY,
    CustomerID INT NOT NULL,
    EventID INT NOT NULL,
    TicketCount INT NOT NULL,
    ReservationDate DATETIME NOT NULL,
    PaymentAmount FLOAT NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    FOREIGN KEY (EventID) REFERENCES Events(EventID)
);
